language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - make lint
  - make test
env:
  - DJANGO_VERSION=1.8.2
sudo: false
notifications:
  email: false
