language: python
install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - make lint
  - make test-coverage
after_success:
  - make coveralls
sudo: required
dist: xenial
notifications:
  email: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=2.1
