language: python
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install .[test]
script:
  - make lint
  - make test-coverage
after_success:
  - make coveralls
sudo: required
dist: xenial
notifications:
  email: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
