language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r test_requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO_VERSION
script: make test
env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
